resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: controller
  newName: ghcr.io/carleid-homelab/homelab-operator
  newTag: ad56ad658e4c44c7087b4733ff7b772292b1358a
